import os
import sqlite3
import tempfile
from pathlib import Path

from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import Qgis, QgsMessageLog, QgsProject, QgsVectorLayer, QgsWkbTypes


class GpkgGeometryOrganizerPlugin:
    def __init__(self, iface):
        self.iface = iface
        self.action = None
        self.menu = self.tr("&GPKG Geometry Organizer")
        self.icon_path = Path(__file__).resolve().parent / "icons" / "gpkg_organizer.svg"

    def tr(self, text):
        return QCoreApplication.translate("GpkgGeometryOrganizerPlugin", text)

    def initGui(self):
        self.action = QAction(
            QIcon(str(self.icon_path)),
            self.tr("Organize GeoPackage by Geometry + Default Styles"),
            self.iface.mainWindow(),
        )
        self.action.triggered.connect(self.run)
        self.iface.addPluginToMenu(self.menu, self.action)
        self.iface.addToolBarIcon(self.action)

    def unload(self):
        if self.action is None:
            return
        self.iface.removePluginMenu(self.menu, self.action)
        self.iface.removeToolBarIcon(self.action)
        self.action = None

    def _message(self, text, level=Qgis.Info, duration=10):
        self.iface.messageBar().pushMessage(
            "GPKG Geometry Organizer",
            text,
            level=level,
            duration=duration,
        )
        QgsMessageLog.logMessage(text, "GPKGGeometryOrganizer", level)

    def _list_feature_tables(self, gpkg_path):
        with sqlite3.connect(gpkg_path) as conn:
            rows = conn.execute(
                """
                SELECT table_name
                FROM gpkg_contents
                WHERE data_type='features'
                ORDER BY table_name
                """
            ).fetchall()
        return [row[0] for row in rows if row and row[0]]

    def _build_default_qml_templates(self):
        templates = {}
        temp_files = []
        specs = {
            "point": "Point?crs=EPSG:4326",
            "line": "LineString?crs=EPSG:4326",
            "polygon": "Polygon?crs=EPSG:4326",
        }

        for key, uri in specs.items():
            layer = QgsVectorLayer(uri, f"__default_{key}__", "memory")
            if not layer.isValid():
                raise RuntimeError(f"Could not create default {key} style template.")

            with tempfile.NamedTemporaryFile(suffix=".qml", delete=False) as f:
                qml_path = f.name
            _, ok = layer.saveNamedStyle(qml_path)
            if not ok:
                raise RuntimeError(f"Could not save default {key} style to temporary QML.")

            templates[key] = qml_path
            temp_files.append(qml_path)

        return templates, temp_files

    def _geometry_bucket(self, layer):
        geom_type = QgsWkbTypes.geometryType(layer.wkbType())
        if geom_type == Qgis.GeometryType.Point:
            return "point"
        if geom_type == Qgis.GeometryType.Line:
            return "line"
        if geom_type == Qgis.GeometryType.Polygon:
            return "polygon"
        return "other"

    def _apply_default_geometry_style(self, layer, bucket, qml_templates):
        if bucket not in qml_templates:
            return None

        _, ok = layer.loadNamedStyle(qml_templates[bucket])
        if not ok:
            return "could not load default geometry style template"

        style_name = f"DEFAULT_{bucket.upper()}_STYLE"
        layer.saveStyleToDatabase(
            style_name,
            "Default geometry style generated by GPKG Geometry Organizer",
            True,
            "",
        )
        return None

    def _prepare_layer_tree_groups(self, gpkg_path):
        root = QgsProject.instance().layerTreeRoot()
        group_name = f"GPKG: {Path(gpkg_path).stem}"
        existing = root.findGroup(group_name)
        if existing is not None:
            root.removeChildNode(existing)

        parent = root.addGroup(group_name)
        return {
            "point": parent.addGroup("Points"),
            "line": parent.addGroup("Lines"),
            "polygon": parent.addGroup("Polygons"),
            "other": parent.addGroup("Others"),
        }

    def _load_layers_group_and_style(self, gpkg_path, table_names, qml_templates):
        project = QgsProject.instance()
        groups = self._prepare_layer_tree_groups(gpkg_path)

        loaded = 0
        invalid = []
        style_errors = []
        by_bucket = {"point": 0, "line": 0, "polygon": 0, "other": 0}

        for table_name in table_names:
            layer = QgsVectorLayer(
                f"{gpkg_path}|layername={table_name}",
                table_name,
                "ogr",
            )
            if not layer.isValid():
                invalid.append(table_name)
                continue

            bucket = self._geometry_bucket(layer)
            by_bucket[bucket] += 1

            project.addMapLayer(layer, False)
            groups[bucket].addLayer(layer)
            loaded += 1

            error = self._apply_default_geometry_style(layer, bucket, qml_templates)
            if error:
                style_errors.append(f"{table_name}: {error}")

        if loaded == 0:
            raise RuntimeError("No valid vector layers were loaded from the selected GeoPackage.")

        return loaded, by_bucket, invalid, style_errors

    def run(self):
        gpkg_path, _ = QFileDialog.getOpenFileName(
            self.iface.mainWindow(),
            self.tr("Select GeoPackage"),
            str(Path.home()),
            self.tr("GeoPackage (*.gpkg)"),
        )
        if not gpkg_path:
            return

        try:
            tables = self._list_feature_tables(gpkg_path)
        except Exception as exc:
            self._message(f"Could not read GeoPackage tables: {exc}", level=Qgis.Critical, duration=12)
            return

        if not tables:
            self._message("No feature layers found in the selected GeoPackage.", level=Qgis.Warning)
            return

        temp_files = []
        try:
            qml_templates, temp_files = self._build_default_qml_templates()
            loaded, by_bucket, invalid, style_errors = self._load_layers_group_and_style(
                gpkg_path,
                tables,
                qml_templates,
            )
        except Exception as exc:
            self._message(str(exc), level=Qgis.Critical, duration=12)
            return
        finally:
            for path in temp_files:
                if os.path.exists(path):
                    os.remove(path)

        if invalid:
            QgsMessageLog.logMessage(
                "\n".join([f"Invalid layer: {name}" for name in invalid]),
                "GPKGGeometryOrganizer",
                Qgis.Warning,
            )

        if style_errors:
            QgsMessageLog.logMessage(
                "\n".join(style_errors),
                "GPKGGeometryOrganizer",
                Qgis.Warning,
            )

        self._message(
            (
                f"Loaded {loaded} layer(s). "
                f"Points: {by_bucket['point']}, Lines: {by_bucket['line']}, "
                f"Polygons: {by_bucket['polygon']}, Others: {by_bucket['other']}. "
                f"Style warnings: {len(style_errors)}."
            ),
            level=Qgis.Success,
            duration=12,
        )
