# -*- coding: utf-8 -*-
"""
/***************************************************************************
 APCPlan
                                 A QGIS plugin
 APC Plan
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-04
        copyright            : (C) 2025 by BGP Oman
        email                : alshiblih@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load APC class from file APC.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .APC_Plan import APCPlan
    return APCPlan(iface)
